# Generated by Django 4.0.5 on 2023-04-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default='ajay', max_length=100),
            preserve_default=False,
        ),
    ]
